services:
  - type: web
    name: sinatra
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec ruby main.rb
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
  - type: redis
    name: lightning
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: redis
    name: lightning-staging
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
